#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Apuntes de Macroeconometría  # The title of the book. Will be placed in the left navbar.
author                      : Randall Romero Aguilar  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

only_build_toc_files: true

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache



sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js


parse:
  myst_enable_extensions:
    - deflist
    - amsmath
    # - colon_fence
    - dollarmath
    - substitution

bibtex_bibfiles:
   - references.bib

latex:
  latex_engine              : xelatex


#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/randall-romero/econometria  # The URL to your book's repository
  path_to_book              : "."  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

