name: libro-ec4301
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - runjb
  - numpy
  - pandas
  - statsmodels
  - matplotlib
  - plotly
  - sympy
  - nodejs
  - seaborn
  - pandas-datareader
  - pip:
    - bccr
    - macrodemos
    - jupyter-book>=0.7.0b
